### ISSUE TITLE
Certain websites cause threshold to fail

### ISSUE THREAD

**Issue by jasonuher** [ertug/autohidpi#11]
Certain website seem to be doing weird things with the availableWidth value.

The addon works great most of the time, but a few sites (namely: gmail and facebook) will cause the tab to switch back to the default pxper value.

Hangouts, google docs, and youtube seem to work fine, so it seems to be restricted to gmail (meaning it's not something they do in the core framework)

I'm using 1.2.1-signed on FF 44.02, ubuntu wiley with i3 window manager ver 4.11

**Comment by ertug** [comment]
I recently experienced this issue with a website and it turned out that I changed the zoom level by accident. :)
Can you try resetting zoom?
