### ISSUE TITLE
Toggle button?

### ISSUE THREAD

**Issue by rahilwazir** [ertug/autohidpi#14]
It would be better to provide a button to toggle this property regardless of options in the preferences?

**Comment by ertug** [comment]
Why? If it isn't working correctly, please elaborate.

**Comment by rahilwazir** [comment]
@ertug No it is working correctly, I was suggesting an optional button for it, I sometimes don't have retina screen to test, so having an option would be better?

**Comment by ertug** [comment]
If I understand you correctly, you want to do development on the addon and want to test it?
You can make it switch by setting the hidpi screen width preference to something less than your current screen width minus 128 (slack).

**Comment by ertug** [comment]
Now it has a button but does more than just toggling.

**Comment by rahilwazir** [comment]
@ertug Thanks that I was talking about!
