### ISSUE TITLE
Autohidpi stopped working on FF 46.0.1

### ISSUE THREAD

**Issue by robertsawko** [ertug/autohidpi#15]
Hi,

I am really grateful for this addon and it helped me a lot with my current office setup, but in the last week, it seems, the automatic rescaling stopped working completely. Last week I have updated the system but it seems it's only linux and libmagic. I am on an old Ubuntu 14.04, but running xmonad as the window manager and no Unity. I manually change the screen with xrandr when I connect to my retina screen.

**Comment by ertug** [comment]
Hi,
You noticed the new toolbar button, right?
If it is something else, please give more info.

**Comment by robertsawko** [comment]
Sorry, I didn't notice as I am on vimperator too so had a minimal - no add on - setting. Yes, this is now fixed. Thanks.
