### ISSUE TITLE
Changes are permanent, and even removing extension do not cancel behaviour

### ISSUE THREAD

**Issue by jyavenard** [ertug/autohidpi#17]
I installed the extension on Linux, where it works perfectly (but I only have one screen there so couldn't verify if it would be any different).

Having firefox sync enabled, it automatically installed the extension on my mac (dual screen, one 27" 4K and on 27" 2560x1440).

It totally screwed up the 4K display making the menus and fonts utter unreadable. Worse, when moving a window from one screen to the next, it causes to only repaint 1/4 of the window once moved into the 4K screen.

I managed to have it displayed properly on the 4K screen by setting the zoom ratio in the app to 2X ; however then, the text in window on the 2560x1440 screen now all appear twice as big as it should.

If I change the configuration back to 1X so it displays well on the 2560x1440, then it becomes once again unreadable on the 4K screen.

disabling or removing the extension made no difference, the changes made appear permanent.

**Comment by ertug** [comment]
Firefox on mac supports automatic scaling therefore the add-on doesn't needed. It sets layout.css.devPixelsPerPx to 1 which disables automatic scaling. You can go to about:config and reset it to -1.
