### ISSUE TITLE
Strange behavior on debian jessie

### ISSUE THREAD

**Issue by dx486** [ertug/autohidpi#8]
I am using debian jessie (stable) and Iceweasel (Firefox) 31.8.0 with AutoHDPI 1.2.1.

When I run Iceweasel firstly after boot, AutoHDPI does not work. I mean, scaling is not in effect.
Then I close Iceweasel and restart, it works. 
Then I restart Iceweasel, and it stops working.
Then I restart Iceweasel, and it works.

This is keep going like this.

Scaling sometimes becomes inactive upon reactivating Firefox window. It happens randomly as it seems. Restarting Firefox solves this error temporarily.

**Comment by ertug** [comment]
Thank you!
Please try the new version, it should be fixed:
https://addons.mozilla.org/en-US/firefox/addon/autohidpi/versions/?page=1#version-2.0.0
