### ISSUE TITLE
I've got two monitors with the same resolution but different DPI

### ISSUE THREAD

**Issue by graingert** [ertug/autohidpi#9]
So this doesn't work very well, is there other information the addon can access to get the actual DPI of the monitor?

**Comment by ertug** [comment]
That's unfortunate, it's not possible in Linux (X11) because there is only one DPI setting.

**Comment by graingert** [comment]
I know the geometry of my windows, so it would be nice if I could declare rectangles where the DPI changes and have that reflected with this plugin

**Comment by ertug** [comment]
I have an idea to identify screens using its geometry and allow setting pixel ratios for each of them in a user-friendly manner. Stay tuned! :)

**Comment by ertug** [comment]
Now you can set the pixel ratio regardless of your screen resolution, you should try the latest version!
